library(tidyverse)
cat("Darbinė direktorija:", getwd())
download.file("https://atvira.sodra.lt/imones/downloads/2023/monthly-2023.csv.zip", "../data/temp")
unzip("../data/temp",  exdir = "../data/")
file.remove("../data/temp")
file.remove("../data/monthly-2023.csv")
